package com.patipets.core.domain.enums;

public enum TipoNotificacion {
    ALERTA_URGENTE,
    CAMBIO_ESTADO_SOLICITUD,
    CAMBIO_ESTADO_REFUGIO,
    INSCRIPCION_VOLUNTARIADO_CANCELADA,
    INSCRIPCION_VOLUNTARIADO_ACEPTADA,
    INSCRIPCION_VOLUNTARIADO_RECHAZADA,
    APADRINAMIENTO_CANCELADO_POR_REFUGIO,
    APADRINAMIENTO_CANCELADO_POR_PADRINO
}
